name: Build FFmpeg.wasm (Single Thread)
on:
  push:
    branches:
      - n4.3.1-wasm
  pull_request:
    branches:
      - n4.3.1-wasm

env:
  FFMPEG_ST: yes
  DIST_PATH: wasm/packages/core-st/dist
  CACHE_KEY_PREFIX: ffmpeg.wasm-core-st
  # EM_VERSION: 2.0.8
  # EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build-libs:
    strategy:
      max-parallel: 1
      matrix:
        script:
          - build-zlib
          - build-x264
          - build-x265
          - build-libvpx
          - build-wavpack
          - build-lame
          - build-fdk-aac
          - build-ogg
          - build-vorbis
          - build-theora
          - build-opus
          - build-libwebp
          - build-freetype2
          - build-fribidi
          - build-harfbuzz
          - build-libass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Prepare ccache timestamp
        run: echo "TIMESTAMP=$(date +"%s")" >> $GITHUB_OUTPUT
      - name: Cache ccache files
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}-$TIMESTAMP
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref }}-
            ${{ runner.os }}-ccache-
      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Cache libs
        uses: actions/cache@v3
        with:
          path: |
            build
            wasm/cache
          key: ${{ env.CACHE_KEY_PREFIX }}-$COMMIT_HASH-${{ matrix.script }}
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-$COMMIT_HASH-
      - name: List cached libs
        run: ls -R build || true
      - name: Build FFMpeg Libs
        run: bash build-with-docker.sh install-deps ${{ matrix.script }}
  build-ffmpeg:
    runs-on: ubuntu-latest
    needs: build-libs
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get commit hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            build
            wasm/cache
          key: ${{ env.CACHE_KEY_PREFIX }}-$COMMIT_HASH-ffmpeg
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-$COMMIT_HASH-
      - name: List cached libs
        run: ls -R build || true
      - name: Build FFMpeg
        run: |
          bash build-with-docker.sh \
            install-deps \
            configure-ffmpeg \
            build-ffmpeg
      - uses: actions/upload-artifact@master
        with:
          name: ffmpeg-core
          path: ${{ env.DIST_PATH }}
